global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Trading Backend Monitoring Configuration
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Trading API monitoring
  - job_name: 'trading-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # System metrics (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # Container metrics (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # PM2 metrics (if available)
  - job_name: 'pm2'
    static_configs:
      - targets: ['host.docker.internal:9209']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Trading Engine specific metrics
  - job_name: 'trading-engine-health'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/health'
    scrape_interval: 30s

# Alerting rules (can be expanded later)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Remote write configuration (for external monitoring)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint" 